config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :private_maps
  # resources :public_maps
  resources :visits

  root "pages#index"
  get "/about" => "pages#about", as: :about
  get "/contact" => "pages#contact", as: :contact

  get "/signup" => "registrations#new", as: :signup
  post "/signup" => "registrations#create"
  get "/signin" => "authentication#new", as: :signin
  post "/signin" => "authentication#create"
  get "/signout" => "authentication#destroy", as: :signout

  get "/countries" => "countries#index"

  get "/clicked" => "private_maps#clicked"
  post "/clicked" => "private_maps#clicked"

  get "/public_maps" => "public_maps#index"
  get "/country_info/:code" => "public_maps#get_things"
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :visit
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :visit

end

app/models/country.rb
class Country < ActiveRecord::Base

  has_many :visits
  has_many :blogs, through: :visits
  has_many :comments, through: :visits
  has_many :photos, through: :visits

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  mount_uploader :photo, PhotoUploader

  belongs_to :visit

end

app/models/private_map.rb
class Private_Map < ActiveRecord::Base


end

app/models/public_map.rb
class Public_Map < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  has_secure_password

  has_many :visits
  has_many :countries, :through => :visits

  def full_name
    "#{first_name} #{last_name}"
  end

  def has_visited?(country)
    self.visits.where(country_id: country).count != 0
  end

  def visited_country_codes
    self.countries.map do |country|
      country.code.downcase
    end
  end

end

app/models/visit.rb
class Visit < ActiveRecord::Base

  belongs_to :user
  belongs_to :country
  has_many :blogs, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :photos, :dependent => :destroy

end

app/controllers/Private_Maps_controller.rb
class PrivateMapsController < ApplicationController
end

app/controllers/Public_Maps_controller.rb
class PublicMapsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :require_login

  def current_user
    User.find_by(id: session[:user_id])
  end

  helper_method :current_user
  protect_from_forgery with: :exception

  class AccessDenied < StandardError
  end

  rescue_from AccessDenied, with: :render_404


  private

  def render_404
    render "public/404", status: 404, layout: false
  end

  def require_login
    unless current_user
      redirect_to signin_path
    end
  end

end

app/controllers/authentication_controller.rb
class AuthenticationController < MarketingController

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to private_maps_path
    else
      @sign_in_error = "Username / password combination is invalid"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/countries_controller.rb
class CountriesController < MarketingController

  def index
    @countries = Country.all
  end

  private

  def country_params
    params.require(:country).permit(:region, :code)
  end

end

app/controllers/marketing_controller.rb
class MarketingController < ApplicationController

  skip_before_action :require_login

end

app/controllers/pages_controller.rb
class PagesController < MarketingController

end

app/controllers/private_maps_controller.rb
class PrivateMapsController < ApplicationController

  ## what countries have they visited and what are those ids?
  def index
    @visit = Visit.new
  end

  def create
    @countries = Country.all
    @visits = Visit.all

    visited_countries = []
    params[:countries].each do |clicked_country|
      @countries.each do |country|
        if clicked_country.upcase == country.code
          visited_countries << country.id
        end
      end
    end

    visited_countries.each do |visited_country|
      next if current_user.has_visited?(visited_country)
      Visit.create!(user_id: current_user.id, country_id: visited_country)
    end

    current_user.visits.each do |visit|
      if !params[:countries].include?(visit.country.code.downcase)
        visit.destroy!
      end
    end

    # return json for the javascript ajax calls
    render json: params
    # render js: "window.location.pathname='#{jobs_path}'"
    # format.json { render :json => {:result => 'success',  :redirect => root_path } }
  end

  def clicked
    render json: current_user.visited_country_codes
  end

end

app/controllers/public_maps_controller.rb
class PublicMapsController < ApplicationController

  def get_things
    country = Country.where(code: params[:code].upcase).first
    render json: { photos: country.photos, blogs: country.blogs, comments: country.comments }
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < MarketingController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to private_maps_path
    else
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :avatar)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize_admin

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "#{@user.full_name} was successfully created."
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to users_path, notice: 'User was successfully updated.'
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end


  private

  def authorize_admin
    unless current_user.admin?
      raise AccessDenied
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :avatar, :admin)
  end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  def create
    country_code = params[:visit][:country_code]
    country = Country.where(code: country_code.upcase).first
    visit = if current_user.has_visited?(country)
      Visit.where(country_id: country.id, user_id: current_user.id).first
    else
      Visit.create!(country_id: country.id, user_id: current_user.id)
    end

    if saved
      redirect_to private_maps_path, notice: "Country Info Was Successfully Saved"
    else
      redirect_to private_maps_path, notice: "Oops, There Was a Problem.  Please Try Again."
    end
  end

  def show
    @visit = Visit.find(params[:id])
  end

  def update
    @visit = Visit.find(params[:id])
    unless params[:blog] == ""
      blog = Blog.new(visit_id: @visit.id, site: params[:blog])
      blog.save
    end
    unless params[:comment].nil?
      comment = Comment.new(visit_id: @visit.id, comment: params[:comment])
      comment.save
    end
    unless params[:photo].nil?
      photo = Photo.new(visit_id: @visit.id, photo: params[:photo])
      photo.save
    end
    redirect_to visit_path(@visit)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title(title, &block)
    content_for(:title, title)

    html = '<div>'.html_safe

    if block
      html += '<div class ="pull-right">'.html_safe
      html += capture do
        block.call
      end
      html += '</div>'.html_safe
    end

    html += '<h1>'.html_safe
    html += title
    html += '</h1>'.html_safe
    html += '</div>'.html_safe
    html
  end

end

app/views/authentication/new.html.erb
<% @body_class="authentication-page" %>
<% page_title "Sign In" %>



<%= form_tag(signin_path) do |f| %>
  <div class="container signin well col-sm-offset-3 col-sm-6">

    <h1 class="form-signin-heading text-center">Sign Into
      <span style="color: orange">mucklucks</span></h1>

    <div class="text-danger">
      <% if @sign_in_error %>
        <p><%= @sign_in_error %></p>
      <% end %>
    </div>

    <div class="form-group">
        <label for="email" class="col-sm-2">Email</label>
      <div class="col-sm-8">
        <%= email_field_tag :email, nil, class: "form-control col-sm-1 " %>
      </div>
    </div>

    <br>
    <br>

    <div class="form-group password">
        <label for="password" class="col-sm-2">Password</label>
      <div class="col-sm-8">
        <%= password_field_tag :password, nil, class: "form-control col-sm-offsetcol-sm-1" %>
      </div>
    </div>

    <br>
    <br>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-5">
      <%= submit_tag "Sign In", class: "auth-button btn btn-default" %>
      </div>
    </div>

    <div>
      <h2 class="col-sm-offset-1 col-sm-10 text-center">Don't have an account yet?
        <%= link_to "Sign Up", signup_path %></h2>
    </div>

  </div>
<% end %>

app/views/countries/index.html.erb
<% @body_class="countries_index-page" %>



<div class= "container countries_page col-sm-offset-1">
  <center><%= page_title "Countries" do %>
    <% end %></center>

  <table class="countries table table-hover">
    <thead>
      <tr>
        <th>Region</th>
        <th>Code</th>
      </tr>
    </thead>
    <tbody>
      <% @countries.each do |country| %>
      <tr>
        <td><%= country.region %></td>
        <td><%= country.code %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/private_maps/index.html.erb
<% @body_class="private-page" %>
<% page_title "Private Map" %>

<input type="hidden" name="visit[country_code]" value="" class="visit_form_country_code">
<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

<div class="text-center">
  <h1>Welcome to the Private Map, <%= "#{current_user.first_name}" %>
    <% if current_user.avatar.present? %>
      <%= image_tag current_user.avatar, class: "img-responsive img-thumbnail", size: "120x80" %>
    <% end %>
  </h1>
</div>

<div class="select">
  <h1>Please Select a Country</h1>
</div>

<div id="vmap"></div>

<div class="ajax-button save-fields">
  <button id="ajax-get">Submit</button>
</div>

  <div class="row-list">
    <div>
      <h2 class="center">You have been to:</h2>
      <% current_user.visits.each do |visit| %>
        <h4><%= link_to visit.country.region, visit_path(visit) %></h4>
      <% end %>
    </div>
  </div>

</div>

</form>

app/views/public_maps/index.html.erb
<% @body_class="public-page" %>
<% page_title "Public Map" %>

<div class="text-center">
  <h1>Welcome to the Public Map, <%= "#{current_user.first_name}" %>
    <% if current_user.avatar.present? %>
      <%= image_tag current_user.avatar, class: "img-responsive img-thumbnail", size: "120x80" %>
    <% end %>  </h1>
</div>

<div class="select">
  <h1>Please Select a Country</h1>
</div>

<div id="vmap2"></div>

  <div class="information col-xs-12 col-sm-12">
    <h2><font color="orange">mucklucks</font> Users:</h2>
      <div class="jumbotron public text-center pull-right">

        <div class="col-xs-6 col-lg-4 blogs">
          <h2><font color="orange">mucklucks</font> Blogs:</h2>
          <p>Read memories, accounts, and stories of users who have been to <span class="country_name">COUNTRY</span>. </p>
        </div>

        <div class="col-xs-6 col-lg-4 comments">
          <h2><font color="orange">mucklucks</font> Advice:</h2>
          <p>Glean advice about travel in <span class="country_name">COUNTRY</span> from the perfect source...travelers. </p>
        </div>

        <div class="col-xs-6 col-lg-4 photos">
          <h2><font color="orange">mucklucks</font> Photos:</h2>
          <p>Peruse through photographs in <span class="country_name">COUNTRY</span> uploaded and shared by other users. </p>
        </div>
      </div>

  </div>



<!-- <p><a class="btn btn-default" href="#" role="button">Photos &raquo;</a></p> -->

  <!-- <h2>General Info:</h2>
    <div class="jumbotron public text-center pull-right">
      <div class="col-xs-6 col-lg-4">
        <h2>Wikipedia:</h2>
        <p>Learn basic information about <span class="country_name">COUNTRY</span> - written by the public, for the public. </p>
        <p><a class="btn btn-default" href="#" role="button">Wikipedia &raquo;</a></p>
      </div>
      <div class="col-xs-6 col-lg-4">
        <h2>CDC:</h2>
        <p>Explore relevant travel information for <span class="country_name">COUNTRY</span> - including recommended vaccines, medicine, and packing lists. </p>
        <p><a class="btn btn-default" href="#" role="button">CDC &raquo;</a></p>
      </div>
      <div class="col-xs-6 col-lg-4">
        <h2>travel.state.gov:</h2>
        <p>Be informed of <span class="country_name">COUNTRY</span> visa requirements, travel advisories, local heath information, and laws. </p>
        <p><a class="btn btn-default" href="#" role="button">travel.state.gov &raquo;</a></p>
      </div>
    </div>
  <h2>What to Do / Where to Stay:</h2>
    <div class="jumbotron public text-center pull-right">
      <div class="col-xs-6 col-lg-4">
        <h2>TripAdvisor</h2>
        <p>Peruse an extensive collection of <span class="country_name">COUNTRY</span> travel reviews.  Reviews include restaurants, hotels, and sites. </p>
        <p><a class="btn btn-default" href="#" role="button">TripAdvisor &raquo;</a></p>
      </div>
      <div class="col-xs-6 col-lg-4">
        <h2>Couchsurfing:</h2>
        <p>Stay free in the homes of locals passionate about helping travelers have the best experience possible in <span class="country_name">COUNTRY</span>. </p>
        <p><a class="btn btn-default" href="#" role="button">Couchsurfing &raquo;</a></p>
      </div>
      <div class="col-xs-6 col-lg-4">
        <h2>Airbnb:</h2>
        <p>Get a great rate on a room, apartment, or house from a local in <span class="country_name">COUNTRY</span>. </p>
        <p><a class="btn btn-default" href="#" role="button">Airbnb &raquo;</a></p>
      </div>
    </div>
  <h2>Airfare / Weather:</h2>
    <div class="jumbotron public bottom text-center pull-right">
      <div class="col-xs-6 col-lg-4">
        <h2>Skyscanner</h2>
        <p>Search for cheap flights to or from <span class="country_name">COUNTRY</span> using two of the best airfare sites around. </p>
        <a class="btn btn-default" href="#" role="button">Skyscanner &raquo;</a></p>
      </div>
      <div class="col-xs-6 col-lg-4">
        <h2>HipMonk</h2>
        <p>Search for cheap flights to or from <span class="country_name">COUNTRY</span> using two of the best airfare sites around. </p>
        <p><a class="btn btn-default" href="#" role="button">Hipmonk &raquo;</a>
      </div>
      <div class="col-xs-6 col-lg-4">
        <h2>Weather:</h2>
        <p>Explore <span class="country_name">COUNTRY</span> weather data from the past, as well as current forecasts. </p>
        <p><a class="btn btn-default" href="#" role="button">Weather &raquo;</a></p>
      </div>
    </div> -->

app/views/users/_form.html.erb
<% @body_class="users-form-page" %>

<%= form_for(@user, html: {class: "form-horizontal"}) do |f| %>
  <div class="container signup well col-sm-offset-3 col-sm-6">

    <center><%= page_title "#{title}" %></center>

    <% if @user.errors.present? %>
      <ul class= "list list-unstyled text-danger">
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <div class="form-group">
      <label class="col-sm-2 control-label"><%= f.label :first_name %></label>
      <div class="col-sm-8">
        <%= f.text_field :first_name, class: "form-control col-sm-4" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label"><%= f.label :last_name %></label>
      <div class="col-sm-8">
        <%= f.text_field :last_name, class: "form-control col-sm-4" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label"><%= f.label :email %></label>
      <div class="col-sm-8">
        <%= f.email_field :email, class: "form-control" %>
      </div>
    </div>

  <% if @user.id.nil? %>
    <div class="form-group">
      <label class="col-sm-2 control-label"><%= f.label :password %></label>
      <div class="col-sm-8">
        <%= f.password_field :password, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label"><%= f.label :password_confirmation %></label>
      <div class="col-sm-8">
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
    </div>
    <% end %>

    <div class="form-group">
      <label class="col-sm-2 control-label"><%= f.label :avatar %></label>
      <div class="col-sm-8">
        <%= f.file_field :avatar, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-5">
        <%= f.check_box :admin %>
        <%= f.label :admin %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-5">
        <%= f.submit class:"auth-button btn btn-default" %>
      </div>
    </div>

  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form', title: "Edit User" %>

app/views/users/index.html.erb
<% @body_class="users_index-page" %>

<div class= "container users_page">
  <center><%= page_title "Users" do %>
    <%= link_to "Create User", new_user_path, class: "btn btn-default pull-right" %>
    <% end %></center>

  <hr>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= link_to ("#{user.first_name} #{user.last_name}"),
        user_path(user), class: "name_link" %></td>
        <td><%= user.email %></td>
        <td><%= link_to "Edit", edit_user_path(user),
        class:"auth-button btn btn-default" %></td>
        <td><%= link_to "Delete", user, method: :delete,
        data: { confirm: "Are you sure?"}, class: "auth-button btn btn-default" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<%= render 'form', title: "New User" %>

app/views/users/show.html.erb
<% @body_class="users-show-page" %>

<div class="jumbotron show text-center col-sm-offset-3 col-sm-6">

  <%= page_title "#{@user.first_name} #{@user.last_name}" %>

  <br>

  <strong>
      <div class="form-group col-sm-offset-1">
        <%= image_tag @user.avatar, class: "img-responsive img-thumbnail",
        size: "120x80" %>
      </div>

    <div class="form-group col-sm-offset-1">
    Email: <%= mail_to @user.email %>
    </div>
  </strong>

  <div><%= link_to "Edit", edit_user_path(@user),
      class:"auth-button btn btn-default" %>
    <%= link_to "Delete", @user, method: :delete, data: { confirm: "Are you sure?"},
      class: "auth-button btn btn-default" %>
  </div>

</div>

app/views/visits/show.html.erb
<% @body_class="visit-page" %>
<% page_title @visit.country.region %>
<!-- <form id="form_id" action="/visits/" method="patch" enctype="multipart/form-data">
<%= hidden_field_tag :authenticity_token, form_authenticity_token -%> -->


<h2 class="country-show-title"><%= current_user.first_name %>'s Time in <%= @visit.country.region %></h2>


  <%= form_for @visit, :html => {:multipart => true} do |f| %>

<div class="advice-show">
  <h3>Advice</h3>
  <% @visit.comments.each do |comment| %>
    <p><%= comment.comment %></p>
  <% end %>
  <div class="add-fields">
    <div class="field">
      <textarea name="comment" rows="8" cols="40" class="advice-field"></textarea>
    </div>
    <div class="submit-field-area">
      <input type="submit" class="submit-field">
    </div>
  </div>
</div>

<div class="blog-show">
  <h3>Blog</h3>
  <% @visit.blogs.each do |blog| %>
    <a class="blog-site" href="<%= "http://#{blog.site}" %>"><%= blog.site %></a>
  <% end %>
  <div class="add-fields">
    <div class="field">
      <input type="text_field" maxlength="250" name="blog">
    </div>
    <div class="submit-field-area">
      <input type="submit" class="submit-field">
    </div>
  </div>
</div>

<div class="photos-show">
  <h3>Photos</h3>
  <% @visit.photos.each do |photo| %>
    <%= image_tag photo.photo, class: "photo-show" %>
  <% end %>
  <div class="add-fields">
    <div class="field">
      <input type="file" name="photo" class="photo-input">
    </div>
    <div class="submit-field-area">
      <input type="submit" class="submit-field">
    </div>
  </div>
</div>

<% end %>