config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :private_maps
  # resources :public_maps
  resources :visits

  root "pages#index"
  get "/about" => "pages#about", as: :about
  get "/contact" => "pages#contact", as: :contact

  get "/signup" => "registrations#new", as: :signup
  post "/signup" => "registrations#create"
  get "/signin" => "authentication#new", as: :signin
  post "/signin" => "authentication#create"
  get "/signout" => "authentication#destroy", as: :signout

  get "/countries" => "countries#index"

  get "/clicked" => "private_maps#clicked"
  post "/clicked" => "private_maps#clicked"

  get "/public_maps" => "public_maps#index"
  get "/country_info/:code" => "public_maps#get_things"
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :visit
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :visit

end

app/models/country.rb
class Country < ActiveRecord::Base

  has_many :visits
  has_many :blogs, through: :visits
  has_many :comments, through: :visits
  has_many :photos, through: :visits

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  mount_uploader :photo, PhotoUploader

  belongs_to :visit

end

app/models/private_map.rb
class Private_Map < ActiveRecord::Base


end

app/models/public_map.rb
class Public_Map < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  has_secure_password

  has_many :visits
  has_many :countries, :through => :visits

  def full_name
    "#{first_name} #{last_name}"
  end

  def has_visited?(country)
    self.visits.where(country_id: country).count != 0
  end

  def visited_country_codes
    self.countries.map do |country|
      country.code.downcase
    end
  end

end

app/models/visit.rb
class Visit < ActiveRecord::Base

  belongs_to :user
  belongs_to :country
  has_many :blogs, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :photos, :dependent => :destroy

end

app/controllers/Private_Maps_controller.rb
class PrivateMapsController < ApplicationController
end

app/controllers/Public_Maps_controller.rb
class PublicMapsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :require_login

  def current_user
    User.find_by(id: session[:user_id])
  end

  helper_method :current_user
  protect_from_forgery with: :exception

  class AccessDenied < StandardError
  end

  rescue_from AccessDenied, with: :render_404


  private

  def render_404
    render "public/404", status: 404, layout: false
  end

  def require_login
    unless current_user
      redirect_to signin_path
    end
  end

end

app/controllers/countries_controller.rb
class CountriesController < MarketingController

  def index
    @countries = Country.all
  end

  private

  def country_params
    params.require(:country).permit(:region, :code)
  end

end

app/controllers/marketing_controller.rb
class MarketingController < ApplicationController

  skip_before_action :require_login

end

app/controllers/pages_controller.rb
class PagesController < MarketingController

end

app/controllers/private_maps_controller.rb
class PrivateMapsController < ApplicationController

  ## what countries have they visited and what are those ids?
  def index
    @visit = Visit.new
  end

  def create
    @countries = Country.all
    @visits = Visit.all

    visited_countries = []
    params[:countries].each do |clicked_country|
      @countries.each do |country|
        if clicked_country.upcase == country.code
          visited_countries << country.id
        end
      end
    end

    visited_countries.each do |visited_country|
      next if current_user.has_visited?(visited_country)
      Visit.create!(user_id: current_user.id, country_id: visited_country)
    end

    current_user.visits.each do |visit|
      if !params[:countries].include?(visit.country.code.downcase)
        visit.destroy!
      end
    end

    # return json for the javascript ajax calls
    render json: params
    # render js: "window.location.pathname='#{jobs_path}'"
    # format.json { render :json => {:result => 'success',  :redirect => root_path } }
  end

  def clicked
    render json: current_user.visited_country_codes
  end

end

app/controllers/public_maps_controller.rb
class PublicMapsController < ApplicationController

  def get_things
    country = Country.where(code: params[:code].upcase).first
    render json: { photos: country.photos, blogs: country.blogs, comments: country.comments }
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < MarketingController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to private_maps_path
    else
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :avatar)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize_admin

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "#{@user.full_name} was successfully created."
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to users_path, notice: 'User was successfully updated.'
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end


  private

  def authorize_admin
    unless current_user.admin?
      raise AccessDenied
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :avatar, :admin)
  end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  def create
    country_code = params[:visit][:country_code]
    country = Country.where(code: country_code.upcase).first
    visit = if current_user.has_visited?(country)
      Visit.where(country_id: country.id, user_id: current_user.id).first
    else
      Visit.create!(country_id: country.id, user_id: current_user.id)
    end

    if saved
      redirect_to private_maps_path, notice: "Country Info Was Successfully Saved"
    else
      redirect_to private_maps_path, notice: "Oops, There Was a Problem.  Please Try Again."
    end
  end

  def show
    @visit = Visit.find(params[:id])
  end

  def update
    @visit = Visit.find(params[:id])
    unless params[:blog] == ""
      blog = Blog.new(visit_id: @visit.id, site: params[:blog])
      blog.save
    end
    unless params[:comment].nil?
      comment = Comment.new(visit_id: @visit.id, comment: params[:comment])
      comment.save
    end
    unless params[:photo].nil?
      photo = Photo.new(visit_id: @visit.id, photo: params[:photo])
      photo.save
    end
    redirect_to visit_path(@visit)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title(title, &block)
    content_for(:title, title)

    html = '<div>'.html_safe

    if block
      html += '<div class ="pull-right">'.html_safe
      html += capture do
        block.call
      end
      html += '</div>'.html_safe
    end

    html += '<h1>'.html_safe
    html += title
    html += '</h1>'.html_safe
    html += '</div>'.html_safe
    html
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <title><%= "Mucklucks | #{content_for(:title)}"  %></title>
  </head>

  <body class="<%= @body_class %>">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-4">
            <ul class="nav navbar-nav navbar-left">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
              <li><%= link_to "Countries", countries_path %></li>
              <% if current_user && current_user.admin %>
                <li><%= link_to "Users", users_path %></li>
              <% end %>
            </ul>
          </div>
          <div class="col-md-4 col-sm-2 col-xs-1">
            <%= link_to "mucklucks", root_path, class:"navbar-brand mucklucks-logo" %>
          </div>
          <div class="col-md-4">
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <li><%= link_to "Private Map", private_maps_path %></li>
                <li><%= link_to "Public Map", public_maps_path %></li>
                <li><%= link_to "Sign Out", signout_path %></li>
              <% else %>
                <li><%= link_to "Sign In", signin_path %></li>
                <li><%= link_to "Sign Up", signup_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </nav>

    <% if notice %>
      <div class="alert alert-info text-center" role= "alert">
          <strong><%= notice %></strong>
      </div>
    <% end %>

    <%= yield %>

    <footer class="footer col-sm-offset-4">
      <div>
          <%= link_to "https://www.linkedin.com/in/lbhasemeyer/" do %>
            <% image_tag("LinkedIn.png", width: "40") %>
          <% end %>
          <%= link_to "https://github.com/lbhasemeyer" do %>
            <% image_tag("GitHub.png", width: "40") %>
          <% end %>
          <%= link_to "https://twitter.com/lkbhas" do %>
            <% image_tag("Twitter.png", width: "40") %>
          <% end %>
        <div class="copywright">
          © 2014 Laura Hasemeyer. All Rights Reserved.
        </div>
      </div>
    </footer>

  </body>

</html>

app/views/pages/about.html.erb
<% @body_class="about-page" %>
<% page_title "About" %>

<div class="jumbotron about text-center pull-right" style="margin-top:50px">
      <h1>About <span style="color: orange">mucklucks</span></h1>
      <p class="lead">In 2013 a 20-something Spanish major left her job to embark
          on a lifelong dream with her husband.  They bought a one-way ticket to
          Thailand, with nothing planned.  Their best travel recomendations
          came from other travelers, hosts, and globe-trotter friends back home.  This site
          was created from a passion for making travel convenient, well-informed, and fun.</p>
</div>

app/views/pages/contact.html.erb
<% @body_class="contact-page" %>
<% page_title "Contact" %>

  <div class="jumbotron contact text-center" style="margin-top:100px">
        <h1>Contact <span style="color: orange">mucklucks</span></h1>
        <p class="lead">We would love to hear from you if you have any constructive
            criticism or words of praise!  We will also read your not-so-constructive
            criticism...but prefer not to.  The easiest way to get in touch is
            to reach out to the creater, Laura, on twitter @lkbhas.</p>
  </div>

app/views/pages/index.html.erb
<% page_title "Home" %>

<div class="container marketing">
  <div class="row circle">
    <div class="col-lg-4">
      <%= image_tag("Chacos.jpeg", :class => "img-circle",
          :style => "width: 200px; height: 200px;") %>
      <h2 class="mucklucks"><span style="color: orange">mucklucks</span></h2>
      <p>Mucklucks was created as a haven for travelers and wanderlusters.
         We believe the best travel knowledge comes from people who have been there.
         Through honest opinions, advice, blogs, pictures, and popular travel sites,
         we hope to make travel research easy, collaborative, and fun.</p>
      <p><a class="btn btn-default" href="#featurette3" role="button">More &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <%= image_tag("Bangladesh.jpeg", :class => "img-circle",
          :style => "width: 200px; height: 200px;") %>
      <h2>public map</h2>
      <p>The public map is the ultimate travel asset.  Simply click on a country
        of interest to glean travel knowledge from other Muckluck users.</p>
      <p><a class="btn btn-default" href="#featurette2" role="button">More &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <%= image_tag("Myanmar.jpeg", :class => "img-circle",
          :style => "width: 200px; height: 200px;") %>
      <h2>private map</h2>
      <p>The private map is ideal for storing travel photos, blogs, and memories.
         Highlight the countries you have been to, with a personal profile of memories
         attached to each.</p>
      <p><a class="btn btn-default" href="#featurette1" role="button">More &raquo;</a></p>
    </div>
  </div>



  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading"><a name="featurette1" class="disabled">Gather your travel memories in one place.</a>
          <span class="index_links"><%= link_to "save", signup_path %></span></h2>
      <p class="lead">Most people keep their travel memories in countless places:
          a blog here, a photo album there...  With the mucklucks private map
          you can gather all your travel memories in one place, organized by country.
          Click countries to change their color so you can visually see countries
          you have been to and countries you have yet to explore!</p>
    </div>
    <div class="col-md-5">
      <%= image_tag("Myanmar.jpeg", :size => "480x320") %>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-5">
      <%= image_tag("Bangladesh.jpeg", :size => "480x320") %>
    </div>
    <div class="col-md-7">
      <h2 class="featurette-heading"><a name="featurette2" class="disabled">Donate your travel knowledge.</a>
          <span class="index_links"><%= link_to "share", signup_path %></span></h2>
      <p class="lead">Choose photos, blogs, and advice from your personal map
          that you would like to pass along to the travel community.  These
          nuggets will be conglomerated to the public map to create the ultimate
          travel resource for globe-trotters worldwide.</p>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">Gather advice from other globe-trotters.
          <span class="index_links"><%= link_to "learn", signup_path %></span></h2>
      <p class="lead">Explore countries on the public map to get ideas and
          advice for your future travel.  See real travelers' blogs, pictures,
          and advice.  You will also find links to well-regarded travel resources
          such as the CDC, US Department of State, Trip Advisor, Couchsurfing,
          and Weatherbase.</p>
    </div>
    <div class="col-md-5">
      <%= image_tag("Thailand.jpeg", :size => "480x320") %>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-5">
      <%= image_tag("Chacos.jpeg", :size => "480x320") %>
    </div>
    <div class="col-md-7">
      <h2 class="featurette-heading"><a name="featurette3" class="disabled">Use your knowledge in the world.</a>
          <span class="index_links"><%= link_to "explore", signup_path %></span></h2>
      <p class="lead">The whole point of this website is to share information
          and get people excited about the world.  Exploration is a gift that
          we encourage you to take hold of.  Use your newfound knowledge to
          safely learn and explore!</p>
    </div>
  </div>

  <hr class="featurette-divider">

  <h3 style="margin-top:150px"><span style="color: orange">mucklucks</span> takes no responsibility for your safety
  during travel.  Please be safe and smart.  We also take no responsibility for any
  bad travel advice or inappropriate content shared on this website.  The postings
  reflect the opinion of the posters, not of <span style="color: orange">mucklucks</span>.
  That being said, we hope you enjoy your time with us!</h3>

</div>